### PR TITLE
163722544 Integrate Slack with TravisCI

### PR DESCRIPTION
**Pull request by niomwungeri-fabrice**
#### What does this PR do?
Integrate Slack with Travis CI
#### Description of Task to be completed?
Add andela channel to the travis yml file
#### How should this be manually tested?

- Raise a PR/Build on Andela/Titan-Devs
- if it success build on Travis you will get a notification on Slack on `#titans-devs` channel

#### What are the relevant pivotal tracker stories?
#163722544
#### Questions:
None

### CODE REVIEW

**Comment by Musigwa-zz** [comment]
> #### What does this PR do?
> Integrate Slack with Travis CI
> 
> #### Description of Task to be completed?
> Add andela channel to the travis yml file
> 
> #### How should this be manually tested?
> Raising a PR or Push a new branch, it will send the status of the build/PR to the Slack channel in this case is `#titans-devs`
> 
> #### What are the relevant pivotal tracker stories?
> #163722544
> 
> #### Questions:
> None

**Review by Musigwa-zz — CHANGES_REQUESTED** [review]
- Please resolve your PR conflicts
- Please consider updating the steps to manually test your work. 
I would recommend rephrasing the description of **How it can be manually tested**
- Always remember to use git naming conventions especially on **git commit messages**
`(Hint)`: compare one of your commit messages => (7155df9e435f8835fef76b15e9b30b524427b1c8) to [https://github.com/andela/bestpractices/wiki/Git-naming-conventions-and-best-practices](url)
- Remember to ignore the unnecessary files like (yarn.lock)

**Review by YvesIraguha — COMMENTED** [review]
Add the changes @Musigwa requested.

**Comment by niomwungeri-fabrice** [comment]
@Musigwa & @YvesIraguha I worked on the changes you requested, can you guys review it again.

**Pull request merged**
